dist: trusty
sudo: false

language: node_js
node_js:
  - "6"
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache"
branches:
  only:
    - master

install:
  - yarn install
script:
  - echo asdsadsdasd
  - export CHROME_BIN=chromium-browser
  - yarn build
  - xvfb-run -a yarn test
